#base image
FROM janvog/gpu_horovod:v1.0

#copy the source file
COPY . /src

#set up the work dirtory
WORKDIR "/src"

ENV PYTHONPATH=/src/hickle/lib/python3.6/site-packages:$PYTHONPATH
ENV HDF5_USE_FILE_LOCKING=FALSE

# COMMAND ENTRY BASH
CMD ["python","kitti_train_horovod.py"]

# run in terminal in source directory: docker build -t wfppdl/parallel_training:v1.0 -f ../docker/Dockerfile_parallel .
